name: Deploy Hugo from Obsidian notes

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Publish Obsidian notes to Github pages
    steps:
      - name: Checkout contents repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive

      - name: Install obsidian-export (cached)
        uses: baptiste0928/cargo-install@v3
        with:
          crate: obsidian-export

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Create content dir if not exists
        shell: bash
        run: mkdir -p ./content

      - name: Export Vault
        shell: bash
        run: obsidian-export --hard-linebreaks ./vault ./content

      - name: Build Hugo
        shell: bash
        run: hugo -DEF --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
